root: true
parser: "@typescript-eslint/parser"
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:svelte/recommended
    - prettier
plugins:
    - "@typescript-eslint"
overrides:
    - files: ["*.svelte"]
      parser: svelte-eslint-parser
      parserOptions:
          parser: "@typescript-eslint/parser"
parserOptions:
    sourceType: module
    ecmaVersion: latest
    extraFileExtensions: [.svelte]
env:
    es2022: true
    browser: true
    node: true
rules:
    "@typescript-eslint/no-explicit-any": 0
    no-undef: 1
