extends: 
  - "stylelint-config-standard"
  - "stylelint-config-recommended-scss"
plugins:
  - "stylelint-scss"
rules:
  selector-class-pattern: null
  color-function-notation: null
  alpha-value-notation: null
  indentation: 4
